version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
      - "25:25"
    volumes:
      - ./mails:/usr/src/app/mails
      - ./public:/var/www/html
      - ./php-mailer:/var/www/html/php-mailer
    environment:
      RECAPTCHA_SITEKEY: ${RECAPTCHA_SITEKEY}
      RECAPTCHA_SECRETKEY: ${RECAPTCHA_SECRETKEY}

volumes:
  storage:
    driver: local
